apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2025-03-14T17:06:45Z"
  generation: 1
  name: ping
  namespace: exam-o-toshev
  resourceVersion: "8454370"
  uid: df47f671-13e4-470b-bd27-2159e1c978f2
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - ping -c 4 8.8.8.8
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            name: ping
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 2 * * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
